import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';

export const appConfig: ApplicationConfig = {
  providers: [provideBrowserGlobalErrorListeners()],
};

export const LOCATIONS = [
  { key: 'Env_ClearingOak_GreenGlade', label: '绿野空地' },
  { key: 'Env_ClearingOak_MossyClearing', label: '覆苔林隙' },
  { key: 'Env_ClearingPine_BadgerHill', label: '獾丘' },
  { key: 'Env_ClearingPine_DeadHollow', label: '死亡幽谷' },
  { key: 'Env_ClearingPine_FlowerGlade', label: '花间空地' },
  { key: 'Env_ClearingPine_HeatherGlade', label: '石南空地' },
  { key: 'Env_ClearingPine_MoonHills', label: '月丘' },
  { key: 'Env_ClearingPine_PineClearing', label: '松树林隙' },
  { key: 'Env_ClearingPine_PineMeadows', label: '松林草场' },
  { key: 'Env_GroveOak_GreenGrove', label: '绿意林地' },
  { key: 'Env_GroveOak_MossyGrove', label: '苔绿林地' },
  { key: 'Env_GroveOak_MuddyGrove', label: '泥泞林地' },
  { key: 'Env_GroveOak_MysteriousGrove', label: '神秘林地' },
  { key: 'Env_GroveOak_OakenGrove', label: '橡木林' },
  { key: 'Env_GroveOak_OldGrove', label: '老树林' },
  { key: 'Env_GroveOak_OldHollow', label: '古旧寂谷' },
  { key: 'Env_GroveOak_PrimevalWoods', label: '原初森林' },
  { key: 'Env_GroveOak_SacredGrove', label: '神圣之森' },
  { key: 'Env_GroveOak_SecretGrove', label: '隐秘林地' },
  { key: 'Env_GroveOak_ShadyGrove', label: '幽荫林地' },
  { key: 'Env_GrovePine_CrowPines', label: '乌鸦松林' },
  { key: 'Env_GrovePine_DeerGrove', label: '鹿鸣松林' },
  { key: 'Env_GrovePine_ElevatedGrove', label: '高架林地' },
  { key: 'Env_GrovePine_HighGrove', label: '高地林地' },
  { key: 'Env_GrovePine_HowlingWoods', label: '狼嚎幽径' },
  { key: 'Env_GrovePine_LakeGrove', label: '湖畔林地' },
  { key: 'Env_GrovePine_MountainGrove', label: '山地林地' },
  { key: 'Env_GrovePine_PeacefulGrove', label: '平和林地' },
  { key: 'Env_GrovePine_PineGrove', label: '松树林地' },
  { key: 'Env_GrovePine_RockyGrove', label: '乱石林地' },
  { key: 'Env_GrovePine_RockyPines', label: '岩脊松林' },
  { key: 'Env_GrovePine_SlopedGrove', label: '坡道林地' },
  { key: 'Env_GrovePine_SwayingPines', label: '摇曳松林' },
  { key: 'Env_GrovePine_WindGrove', label: '风语林地' },
  { key: 'Env_GrovePine_WindNeedles', label: '风针松林' },
  { key: 'Env_GrovePine_WolfPass', label: '狼嚎隘口' },
  { key: 'Env_River_ClearingOak_RiverClearing', label: '河畔林隙' },
  { key: 'Env_River_GroveOak_FloodedGrove', label: '水浸林地' },
  { key: 'Env_River_GroveOak_GreenFalls', label: '绿色瀑布' },
  { key: 'Env_River_GroveOak_MossyBank', label: '覆苔河岸' },
  { key: 'Env_River_ClearingPine_HeatherMarshes', label: '石南沼泽' },
  { key: 'Env_River_GrovePine_HeatherMarshes', label: '石南沼泽' },
  { key: 'Env_River_GrovePine_LakeIsland', label: '湖心岛' },
  { key: 'Env_River_GrovePine_NorthernLakeBank', label: '北部湖岸' },
  { key: 'Env_River_GrovePine_NorthernRapids', label: '北部湍流' },
  { key: 'Env_River_GrovePine_RiverPass', label: '河道隘口' },
  { key: 'Env_River_GrovePine_RockyBank', label: '岩脊河岸' },
  { key: 'Env_River_GrovePine_SouthernLakeBank', label: '南部湖岸' },
  { key: 'Env_River_ThicketOak_MuddyBank', label: '泥泞河岸' },
  { key: 'Env_River_ThicketOak_RiverConfluence', label: '河流交汇处' },
  { key: 'Env_River_ThicketOak_ShadyBank', label: '幽荫河畔' },
  { key: 'Env_River_ThicketPine_SouthernRapids', label: '南部湍流' },
  { key: 'Env_ThicketOak_GreenTangle', label: '纷乱翠林' },
  { key: 'Env_ThicketOak_LostWoods', label: '迷林幽径' },
  { key: 'Env_ThicketOak_MuddyThicket', label: '泥泞丛林' },
  { key: 'Env_ThicketOak_MuddyWay', label: '泥泞小径' },
  { key: 'Env_ThicketOak_OldThicket', label: '古寂丛林' },
  { key: 'Env_ThicketOak_WhisperingThicket', label: '絮语风林' },
  { key: 'Env_ThicketOak_WildTangle', label: '蛮荒杂林' },
  { key: 'Env_ThicketOak_WildThicket', label: '荒野丛林' },
  { key: 'Env_ThicketPine_CliffThicket', label: '断崖丛林' },
  { key: 'Env_ThicketPine_EasternWildWoods', label: '东部荒林' },
  { key: 'Env_ThicketPine_Fangvale', label: '狼牙谷' },
  { key: 'Env_ThicketPine_MountainThicket', label: '山脊丛林' },
  { key: 'Env_ThicketPine_NeedleThicket', label: '松针丛林' },
  { key: 'Env_ThicketPine_PineCliffs', label: '松林峭崖' },
  { key: 'Env_ThicketPine_PineSlopes', label: '松林坡地' },
  { key: 'Env_ThicketPine_ShadyPines', label: '浓荫松林' },
  { key: 'Env_ThicketPine_WesternWildWoods', label: '西部荒林' },
];
